- hosts: localhost
  gather_facts: no
  pre_tasks:
    - name: "Install python2"
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
      become: yes
    - name: Gather facts after py2
      setup:
  roles:
      - flu.assembler
